# Use the base image from Docker Hub
FROM roynirmal/pyndri

# Set the working directory inside the container
WORKDIR /indri-5.11

# Create a volume to mount your local path inside the container
VOLUME ["/indri-5.11"]

# Start the container and keep it running (adjust the entrypoint if needed)
CMD ["/bin/bash"]